### ISSUE TITLE
I got stuck in wall.

### ISSUE THREAD

**Issue by kirillzhosul** [FireSquid6/teleorb-classic#2]
![image](https://user-images.githubusercontent.com/79853674/131252666-a22bfa95-1230-49bc-b0db-41b8fba94764.png)

**Comment by FireSquid6** [comment]
I've been working on debugging this for a while. It has to do with the way the orb manages its collisions and might take a bit to fix. Thank you!

**Comment by FireSquid6** [comment]
I've done some debugging and it should be fixed now. Check the next release later this week for it.
