### ISSUE TITLE
No UI in the last version?

### ISSUE THREAD

**Issue by kirillzhosul** [FireSquid6/teleorb-classic#5]
![teleorb-v0_0_0_rlQvcDydyp](https://user-images.githubusercontent.com/79853674/133383423-a278767a-1055-4cd2-9f56-1aa0cefad5c0.png)
When default state
![teleorb-v0_0_0_VEa8a1fzWb](https://user-images.githubusercontent.com/79853674/133383468-5a785fa7-1734-4ade-8448-167d9b6a0f11.png)
When press escape (pause)

**Comment by FireSquid6** [comment]
should be fixed in [v1.0.1](https://github.com/FireSquid6/teleorb/releases/tag/release-v1.0.1)

**Comment by kirillzhosul** [comment]
Ye, fixed but I got RUN INVALID in my left corner of the screen, does it OK? (I don`t want to search much for that, but I think that is about save versions conflict~?)
